os:
  - linux

dist: focal

language: python
python:
  - "3.9"

services:
  - docker

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update
  - sudo apt-get install libproj-dev proj-data proj-bin  
  - sudo apt-get install libgeos-dev
  - sudo apt-get install -y gdal-bin=3.2.1+dfsg-1~focal0
  - sudo apt-get install -y libgdal-dev=3.2.1+dfsg-1~focal0
  - pip install wheel
  - pip install cython  
  - pip install cartopy
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - pip install GDAL==3.2.1

script:
  - python -m pytest -v
  - cp .env.exemple .env
  - docker-compose up -d
  - docker-compose ps