os:
  - linux

dist: xenial

language: python
python:
  - "3.9"

script:
  - apt-get install libproj-dev proj-data proj-bin  
  - apt-get install libgeos-dev  
  - pip install cython  
  - pip install cartopy 
  - python -m pytest -v