os:
  - linux

dist: xenial

language: python
python:
  - "3.9"

before_install:
  - sudo apt-get install libproj-dev proj-data proj-bin  
  - sudo apt-get install libgeos-dev  
  - pip install cython  
  - pip install cartopy 

script:
  - python -m pytest -v