"""empty message

Revision ID: 50d7b4869474
Revises: 
Create Date: 2021-06-21 19:44:38.463544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d7b4869474'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('ho_id', sa.Integer(), nullable=False),
    sa.Column('ho_longitude', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ho_latitude', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ho_housing_median_age', sa.Integer(), nullable=False),
    sa.Column('ho_total_rooms', sa.Integer(), nullable=False),
    sa.Column('ho_total_bedrooms', sa.Integer(), nullable=False),
    sa.Column('ho_population', sa.Integer(), nullable=False),
    sa.Column('ho_households', sa.Integer(), nullable=False),
    sa.Column('ho_median_income', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('ho_median_house_value', sa.Integer(), nullable=False),
    sa.Column('ho_ocean_proximity', sa.String(length=10), nullable=False),
    sa.Column('ho_created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ho_id')
    )
    op.create_table('model_param',
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('mp_alpha', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('mp_l1_ratio', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('mp_max_iter', sa.Integer(), nullable=False),
    sa.Column('mp_active', sa.Boolean(), nullable=False),
    sa.Column('ho_created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('mp_id')
    )
    op.create_table('user_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('role_permissions', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('user',
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('u_email', sa.String(length=60), nullable=False),
    sa.Column('u_password', sa.String(length=128), nullable=False),
    sa.Column('u_role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u_role_id'], ['user_role.role_id'], ),
    sa.PrimaryKeyConstraint('u_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('user_role')
    op.drop_table('model_param')
    op.drop_table('house')
    # ### end Alembic commands ###
