"""empty message

Revision ID: 9ca4303e2397
Revises: d0b54a5936a8
Create Date: 2021-06-25 09:24:51.685273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca4303e2397'
down_revision = 'd0b54a5936a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('ho_updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('house', 'ho_updated_date')
    # ### end Alembic commands ###
