"""empty message

Revision ID: d0b54a5936a8
Revises: 50d7b4869474
Create Date: 2021-06-22 22:05:51.327658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b54a5936a8'
down_revision = '50d7b4869474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('house', 'ho_total_bedrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('house', 'ho_total_bedrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
