"""empty message

Revision ID: eaa2691fb15a
Revises: 
Create Date: 2021-06-18 12:20:03.322481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa2691fb15a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('ho_id', sa.Integer(), nullable=False),
    sa.Column('ho_longitude', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ho_latitude', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ho_housing_median_age', sa.Integer(), nullable=True),
    sa.Column('ho_total_rooms', sa.Integer(), nullable=True),
    sa.Column('ho_total_bedrooms', sa.Integer(), nullable=True),
    sa.Column('ho_population', sa.Integer(), nullable=True),
    sa.Column('ho_households', sa.Integer(), nullable=True),
    sa.Column('ho_median_income', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ho_median_house_value', sa.Integer(), nullable=True),
    sa.Column('ho_ocean_proximity', sa.String(length=10), nullable=True),
    sa.Column('ho_created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ho_id')
    )
    op.create_table('utilisateur',
    sa.Column('ut_id', sa.Integer(), nullable=False),
    sa.Column('ut_mail', sa.String(length=60), nullable=True),
    sa.Column('ut_password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('ut_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilisateur')
    op.drop_table('house')
    # ### end Alembic commands ###
